POST {{baseUrl}}/auth/register 
Content-Type: application/json

{
  "name": "Cliente teste",
  "email": "cliente@gmail.com",
  "password": "12345678",
  "role": "Client" 
}
###

POST {{baseUrl}}/auth/authenticate
Content-Type: application/json

{
  "email": "cliente@gmail.com",
  "password": "12345678",
  "role": "Client" 
}
###