# @name insertClient
POST {{baseUrl}}/client
Content-Type: application/json
Authorization: Bearer {{authUser.response.body.token}}

{
  "address": {
    "cep": "37500000",
    "street": "BPS",
    "number": 1,
    "district": "Cruzeiro",
    "city": "Itajuba",
    "state": "MG"
  },
  "phone": "11999999999"
}
###

# @name getClient
GET {{baseUrl}}/client
Content-Type: application/json
Authorization: Bearer {{authUser.response.body.token}}
###

# @name getClientById
@clientId = 5fe00fc9e64caff4fda15753
GET {{baseUrl}}/client/{{clientId}}
Content-Type: application/json
Authorization: Bearer {{authUser.response.body.token}}
###

# @name authUser
POST  {{baseUrl}}/auth/authenticate
Content-Type: application/json

{
    "email": "client@gmail.com",
    "password": "12345678",
    "role": "Client"
}
###

# @name authUser
POST  {{baseUrl}}/auth/authenticate
Content-Type: application/json

{
    "email": "professional@gmail.com",
    "password": "12345678",
    "role": "Professional"
}
###